name: Build Android APK

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build APK with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          workdir: mobile

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: planebattle-apk
          path: mobile/bin/*.apk
